### ISSUE TITLE
Failing in yast2-bootloader

### ISSUE THREAD

**Issue by jreidinger** [mvidner/yard-medoosa#1]
repo: https://github.com/yast/yast-bootloader

failure:

```
jreidinger@linux-vvcf:~/prace/yast/bootloader> yardoc
Traceback (most recent call last):
	9: from /usr/bin/yardoc:23:in `<main>'
	8: from /usr/bin/yardoc:23:in `load'
	7: from /usr/lib64/ruby/gems/2.5.0/gems/yard-0.9.14/bin/yardoc:13:in `<top (required)>'
	6: from /usr/lib64/ruby/gems/2.5.0/gems/yard-0.9.14/lib/yard/cli/command.rb:14:in `run'
	5: from /usr/lib64/ruby/gems/2.5.0/gems/yard-0.9.14/lib/yard/cli/yardoc.rb:267:in `run'
	4: from /usr/lib64/ruby/gems/2.5.0/gems/yard-medoosa-0.0.1/lib/yard-medoosa.rb:11:in `run_generate_with_medoosa'
	3: from /usr/lib64/ruby/gems/2.5.0/gems/yard-medoosa-0.0.1/lib/yard/medoosa.rb:49:in `generate_medoosa'
	2: from /usr/lib64/ruby/gems/2.5.0/gems/yard-medoosa-0.0.1/lib/yard/medoosa.rb:49:in `each'
	1: from /usr/lib64/ruby/gems/2.5.0/gems/yard-medoosa-0.0.1/lib/yard/medoosa.rb:54:in `block in generate_medoosa'
/usr/lib64/ruby/gems/2.5.0/gems/yard-medoosa-0.0.1/lib/yard/medoosa.rb:54:in `fetch': key not found: "Bootloader::Stage1Proposal" (KeyError)
Did you mean?  "Bootloader::Stage1Proposal::PPC"
               "Bootloader::Stage1Proposal::X64"
               "Bootloader::Stage1Proposal::S390"
```

**Comment by mvidner** [comment]
Thanks!
I see, the problem is that I haven't decided how to represent namespaces which are also full-blown classes. (y2network has none at the moment)
